### PR TITLE
Working Round Trip, various bits of polishing

### PR DESCRIPTION
**Pull request by drphilmarshall**
@tcollett @jchiang87 I spent the 11 hour flight back to CA finishing off and documenting the code Tom worked on at the Hack Day. I think it's in good shape, see what you think! 

@jchiang87 I implemented the round trip test as a "science test" - I'm hoping this will get us up to 100% coverage ;-) Interested to hear what you think about this approach. Some might say it is extreme, but TBH I am finding it really helpful to be able to continually check that everything works as its supposed to just by pummeling `nosetests` into the command line.

@tcollett The main bit of functionality missing right now as far as TDC2 is concerned is the reading of TDC2-format text files. We can now write them out with correct headers, so with a bit of work on the `read` method we'll be able to make the round trip write out and read in too - and then we'll be ready to test on actual samples returned from `SLTimer`. It turned out to be easy to speed up the individual lens likelihood marginalization, we had basically already written it the way `numpy` likes :-)

### CODE REVIEW

**Comment by tcollett** [comment]
So did you find (and squash) the bug yet Phil?

**Comment by drphilmarshall** [comment]
Yep! The formula relating H0 to dt and Delta_FP was right in one place but not in the other. The updated notebook has the math(s) right, and the code is self consistent and agrees with the math(s).

**Comment by jchiang87** [comment]
@drphilmarshall Could we go ahead and merge this into master?  I'd like to finish #8 and #9, but I think it would be cleaner if we could merge it with these changes first.

**Comment by drphilmarshall** [comment]
Sure, I'll merge this. Travis is still failing, because `scipy` needs `lapack` which seems to require an `apt-get` call that I don't understand yet. [This blogpost](http://danielnouri.org/notes/2012/11/23/use-apt-get-to-install-python-dependencies-for-travis-ci/) looks helpful. I'll issue it!

**Pull request merged**
